```{r}
devtools::load_all()
```

```{r}
create_figure_directory("../", "test")
```


```{r}
calc_magnitude(x = 10000)
calc_magnitude(x = 0.034)
calc_magnitude(x = 0.03400001)
calc_magnitude(x = 0)
calc_magnitude(x = -1.3)
calc_magnitude(x = -0.03)
calc_magnitude(x = -0)
```

```{r}
calc_quantile_range(x = 1:100, lower = 0.1, upper = 0.9)
calc_quantile_range(x = -25:25, lower = 0.25, upper = 0.75)
```

```{r}
pp <- 1:3
cat4(pp) # fails, so removed from rc
```

```{r}
pp <- 1:3
rr <- list("a" = pp, pp)
cat2(pp)
print_line(4)
cat2(rr)
print_line(1)
cat3(pp, "Hi")
print_line("t")
cat3(rr, "Bye")
print_line(2)
cat_list(rr)
print_line(3)
cat_list(pp)
```

```{r}
count_decimal_places(1)
count_decimal_places(1.345)
count_decimal_places(-1.3450)
count_decimal_places(0.4234)
```



```{r}
pp <- 1:3
rr <- list("a" = pp, pp)
tt <- list("a" = rr)
count_list_depth(rr)
count_list_depth(tt)
```

```{r}
fresh("")
```

```{r}
get_extension(filename = "dev01_rc_testing.qmd")
```

```{r}
get_initials(month.abb[6:8])
get_initials(month.abb[6:8], collapse = "-")
```

```{r}
get_latest_git()
get_latest_git(display = FALSE)
b1 <- get_latest_git(display = FALSE, incGitCommit = TRUE) # not sure
b2 <- get_latest_git(display = FALSE, incGitCommit = FALSE) # not sure
b1
print_line()
b2
```

```{r}
pp <- 1:3
rr <- list("a" = pp, pp)
tt <- list("b" = rr)
get_list_names(rr)
get_list_names(rr, name = "imaginary")
get_list_names(tt)
get_list_names(pp)  # fails as not a list
```

```{r}
get_metadata()
m1 <- get_metadata("testing" = "yellow", blurb = "This is a blurb")
m2 <- get_metadata("testing" = "blue", blurb = "json blurb", format = "json")
m3 <- get_metadata("testing" = "blue", blurb = "NetCDF blurb", format = "NetCDF")
m4 <- get_metadata("testing" = "blue", blurb = "PDF blurb", format = "PDF")

cat_list(m1)
cat_list(m2)
cat_list(m3)
cat_list(m4)

```

```{r}
sesh <- sessionInfo()
get_packages(seshInfo = sesh, whichPackages = "base")
print_line()
get_packages(seshInfo = sesh, whichPackages = "namespace")
print_line()
get_packages(seshInfo = sesh, whichPackages = "attached")
```

```{r}
get_sessionInfo()
```

```{r}
make_title_case("this IS a teST.")
```

```{r}
ii <- matrix(1:12, nrow = 3)
print(ii)
print_line()
mirror_matrix_horizontally(ii)
print_line()
mirror_matrix_vertically(ii)
```

```{r}
xx <- 1:5
yy <- 4:9
yy %notIn% xx
yy[yy %notIn% xx]
```

```{r}
print_on_saving("dummyFile.dummy") # doesn't do any checks or save
```

```{r}
tt <- list("a" = month.abb,
           "b" = list("b1" = 1:10,
                      "b2" = letters),
           "c" = month.name)

filename <- "tt_list.json"
save_list(tt, filename = filename) # includes print_on_saving

t2 <- read_list(filename)

cat2(identical(tt, t2))
```

```{r}
# very contrived, pointless example!
for (ii in 1:5) {
  aa <- switch(ii, NULL, 2, NULL, NULL, 6)
  if ((ii %% 2) == 0) {
    aa <- set_if_null(aa, "yep")
  } else {
    aa <- set_if_null(aa, "nooooo")
  }
  print(aa)
}
```

```{r}
kk <- data.frame("a" = 1:10, "b" = 15:24, "c" = 26:35) |> 
  `rownames<-`(paste0("ex", 1:10))

print(kk)
sift(kk, "a > 3")

sift(kk, "a > 3") |>
  sift("c in 27:31") |>
  sift("b != 18")
```

```{r}
test_function()
```

```{r}
start <- start_timer()
for (ii in 1:10) {
  cat(ii)
}
end <- end_timer(start)
```
